on:
  push:
    paths:
      - .github/workflows/sysdig.yml

jobs:
  sysdig-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Get vuln application on image
        uses: actions/checkout@v4
        with:
          repository: sysdiglabs/dummy-vuln-app
  
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest

  	  - name: Get sysdig action repo for the next step
        uses: actions/checkout@v4
        with:
          repository: sysdiglabs/scan-action
          
      - name: Donate MainDB from scan to prevent standalone to fail
        id: donate-db
        uses: sysdiglabs/scan-action@v5
        with:
          # Tag of the image to analyse
          image-tag: sysdiglabs/dummy-vuln-app:latest
          stop-on-failed-policy-eval: false
          stop-on-processing-error: true
          skip-summary: true
  
      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
            image-tag: sysdiglabs/dummy-vuln-app:latest
            standalone: true

      - name: Upload scan logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path:  /home/runner/work/scanning-integration-tests/scanning-integration-tests/scan-logs
  
      - name: Upload SARIF file
        if: success() || failure() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
