on:
  push:
    paths:
      - .github/workflows/sysdig.yml

jobs:
  sysdig-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Get vuln application on image
        uses: actions/checkout@v4
        with:
          repository: sysdiglabs/dummy-vuln-app          
  
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
  
      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v5
        with:
            image-tag: sysdiglabs/dummy-vuln-app:latest
            standalone: true
  
      - name: Upload SARIF file
        if: success() || failure() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
